spring.application.name=ApartmentLedger

server.port=8081
server.servlet.context-path=/al

spring.datasource.url=jdbc:postgresql://localhost:5432/apartment_ledger
spring.datasource.username=youruserID
spring.datasource.password=yourPassword

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# Custom Application Properties
app.tenant.apartment-id=1
app.security.jwt.secret=yourSecretHere
app.security.jwt.expiration-ms=86400000

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Logging
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
